# This is a basic workflow to help you get started with Actions

name: windows-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
  
env:
  VERSION: v1.2.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
#       - name: Test Github Release
#         run: echo ahahaha > test.txt

#       - name: Test Github Release
#         uses: marvinpinto/action-automatic-releases@latest
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: ${{ env.VERSION }}
#           title: Sonolus Server ${{ env.VERSION }}
#           prerelease: false
#           files: |
#             test.txt
            
      - name: Setup C/C++ Compiler
        run: |
          curl "https://ghproxy.com/https://github.com/LittleYang0531/LittleYang0531/releases/download/g++/windows-x64.zip" -o gcc.zip
          unzip gcc.zip
      
      - name: Checking C/C++ Compiler
        run: ./mingw/bin/g++ --version
        
      - name: Compiling Sonolus Server for Windows
        run: |
          ./mingw/bin/g++.exe main.cpp -osonolus -lmysql -lpthread -lcrypto -lssl -lwsock32 -ljson -std=c++14 -O2
          
      - name: Fetching Packages for Sonolus Server
        run: |
          curl "https://ghproxy.com/https://github.com/LittleYang0531/LittleYang0531/releases/download/g++/packages.zip" -o packages.zip
          mkdir packages
          mv packages.zip ./packages
          cd packages
          unzip packages.zip
      
      - name: Checking Sonolus Server for Windows
        run: |
          mv sonolus ./packages
          cd packages
          ./sonolus help

      - name: Packaging Sonolus Server
        run: |
          mv ./config/* ./packages/config/ -f
          mv ./i18n/* ./packages/i18n/ -f
          mv ./web/css ./packages/web/ -f
          mv ./web/js ./packages/web/ -f
          mv ./web/html ./packages/web/ -f
          mv ./CODE_OF_CONDUCT.md ./packages/ -f
          mv ./data.sql ./packages/ -f
          mv ./favicon.ico ./packages/ -f
          mv ./LICENSE.txt ./packages/ -f
          mv ./README.md ./packages/ -f
          mv ./README_en.md ./packages/ -f
          cd packages
          zip windows-x64.zip ./* -R
          
